package com.ifce.edital360.model.enums;

public enum RequirementType {
    ENSINO_MEDIO_COMPLETO,
    ENSINO_SUPERIOR_COMPLETO,
    NACIONALIDADE_BRASILEIRA,
    QUITACAO_MILITAR,
    QUITACAO_ELEITORAL,
    APTIDAO_FISICA,
    APTIDAO_MENTAL,
    EXPERIENCIA_PROFISSIONAL
}
