package com.ifce.edital360.model.enums;

public enum RequirementType {
    FUNDAMENTAL_INCOMPLETO,
    FUNDAMENTAL_COMPLETO,
    MEDIO_INCOMPLETO,
    MEDIO_COMPLETO,
    SUPERIOR_INCOMPLETO,
    SUPERIOR_COMPLETO,
    POS_GRADUACAO,
    MESTRADO,
    DOUTORADO
}
